apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: notebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: demolocal
        image: nginx:1.14.2
        ports:
        - containerPort: 80